CREATE TABLE Slot
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LABEL VARCHAR(255),
    START DATETIME,
    END DATETIME,
    ROOM VARCHAR(100),
    SESSION_ID BIGINT NOT NULL
);

ALTER TABLE Slot ADD FOREIGN KEY (SESSION_ID) REFERENCES Session (ID);
