CREATE TABLE ProposalVote
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    VOTEVALUE VARCHAR(255),
    VOTER_ID BIGINT NOT NULL,
    PROPOSAL_ID BIGINT NOT NULL
);

ALTER TABLE ProposalVote ADD FOREIGN KEY (VOTER_ID) REFERENCES member (ID);
ALTER TABLE ProposalVote ADD FOREIGN KEY (PROPOSAL_ID) REFERENCES proposal (ID);
ALTER TABLE ProposalVote ADD CONSTRAINT uc_voter_proposal UNIQUE (VOTER_ID, PROPOSAL_ID);