CREATE TABLE MemberEvent
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    EVENT_ID BIGINT NOT NULL,
    LEVEL VARCHAR(15)
);

INSERT INTO MemberEvent (MEMBER_ID, EVENT_ID)
SELECT MEMBER_ID,	EVENTS_ID
FROM Member_Event;

UPDATE MemberEvent me set me.level=(SELECT m.level from Member m where m.id=me.member_id);

ALTER TABLE Member DROP COLUMN level;

DROP TABLE Member_Event;