ALTER TABLE Proposal ADD TYPESESSION VARCHAR(255);
ALTER TABLE Proposal DROP COLUMN MAXATTENDEES;
ALTER TABLE Proposal ADD MAXATTENDEES VARCHAR(255);

DROP TABLE Proposal_Member;
CREATE TABLE Proposal_Member
(
    PROPOSAL_ID BIGINT NOT NULL,
    SPEAKERS_ID BIGINT NOT NULL,
    PRIMARY KEY (PROPOSAL_ID, SPEAKERS_ID)
);
ALTER TABLE Proposal_Member ADD FOREIGN KEY (SPEAKERS_ID) REFERENCES Member (ID);
ALTER TABLE Proposal_Member ADD FOREIGN KEY (PROPOSAL_ID) REFERENCES Proposal (ID);
